import { useEffect, useState, useCallback } from 'react';
import { api } from '../lib/api';
import type { ProviderConfig, ProviderConfigSafe } from '../lib/api';
import { getToken } from '../lib/auth';
import ProviderConfigForm from '../components/ProviderConfigForm';
import ModelListEditor from '../components/ModelListEditor';
import { COMMON_MODELS } from '../lib/models';

function generateOrgSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 50);
}

function validateOrgSlug(slug: string): { valid: boolean; error?: string } {
  if (slug.length < 3) return { valid: false, error: 'Slug must be at least 3 characters' };
  if (slug.length > 50) return { valid: false, error: 'Slug must be 50 characters or less' };
  if (!/^[a-z0-9][a-z0-9-]*[a-z0-9]$/.test(slug)) {
    return { valid: false, error: 'Lowercase alphanumeric and hyphens only, no leading/trailing hyphens' };
  }
  return { valid: true };
}

export default function SettingsPage() {
  const [config, setConfig] = useState<ProviderConfigSafe | null>(null);
  const [availableModels, setAvailableModels] = useState<string[] | null>(null);
  const [currentProviderConfig, setCurrentProviderConfig] = useState<ProviderConfig | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [modelSaveStatus, setModelSaveStatus] = useState<'idle' | 'saving' | 'saved' | 'error'>('idle');

  // Org settings state
  const [orgName, setOrgName] = useState('');
  const [orgSlug, setOrgSlug] = useState('');
  const [slugAutoGenerated, setSlugAutoGenerated] = useState(true);
  const [slugError, setSlugError] = useState('');
  const [orgSaveStatus, setOrgSaveStatus] = useState<'idle' | 'saving' | 'saved' | 'error'>('idle');
  const [orgSaveError, setOrgSaveError] = useState('');

  useEffect(() => {
    const token = getToken();
    if (!token) {
      setLoading(false);
      return;
    }
    api.me(token)
      .then(({ tenant }) => {
        setConfig(tenant.providerConfig);
        setAvailableModels(tenant.availableModels ?? null);
        setOrgName(tenant.name ?? '');
        if (tenant.orgSlug) {
          setOrgSlug(tenant.orgSlug);
          setSlugAutoGenerated(false);
        } else {
          setOrgSlug(generateOrgSlug(tenant.name ?? ''));
          setSlugAutoGenerated(true);
        }
      })
      .catch(err => setError(err.message))
      .finally(() => setLoading(false));
  }, []);

  const handleOrgNameChange = useCallback((value: string) => {
    setOrgName(value);
    if (slugAutoGenerated) {
      const newSlug = generateOrgSlug(value);
      setOrgSlug(newSlug);
      if (newSlug) {
        const v = validateOrgSlug(newSlug);
        setSlugError(v.valid ? '' : v.error ?? '');
      } else {
        setSlugError('');
      }
    }
  }, [slugAutoGenerated]);

  const handleSlugChange = useCallback((value: string) => {
    setOrgSlug(value);
    setSlugAutoGenerated(false);
    if (value) {
      const v = validateOrgSlug(value);
      setSlugError(v.valid ? '' : v.error ?? '');
    } else {
      setSlugError('');
    }
  }, []);

  const handleAutoGenerateSlug = useCallback(() => {
    const newSlug = generateOrgSlug(orgName);
    setOrgSlug(newSlug);
    setSlugAutoGenerated(true);
    if (newSlug) {
      const v = validateOrgSlug(newSlug);
      setSlugError(v.valid ? '' : v.error ?? '');
    } else {
      setSlugError('');
    }
  }, [orgName]);

  async function handleOrgSave() {
    if (!orgName.trim()) return;
    if (orgSlug) {
      const v = validateOrgSlug(orgSlug);
      if (!v.valid) {
        setSlugError(v.error ?? '');
        return;
      }
    }

    const token = getToken()!;
    setOrgSaveStatus('saving');
    setOrgSaveError('');
    try {
      await api.updateOrgSettings(token, {
        name: orgName.trim(),
        ...(orgSlug ? { orgSlug } : {}),
      });
      setOrgSaveStatus('saved');
      setSlugAutoGenerated(false);
      setTimeout(() => setOrgSaveStatus('idle'), 2000);
    } catch (err: any) {
      setOrgSaveStatus('error');
      setOrgSaveError(err.message ?? 'Failed to save');
    }
  }

  async function handleSave(providerConfig: ProviderConfig) {
    const token = getToken()!;
    setCurrentProviderConfig(providerConfig);
    const { providerConfig: updated } = await api.updateSettings(token, { ...providerConfig, availableModels });
    setConfig(updated);
  }

  async function handleModelsChange(models: string[] | null) {
    setAvailableModels(models);
    const token = getToken()!;
    setModelSaveStatus('saving');
    try {
      await api.updateSettings(token, {
        ...(currentProviderConfig ?? { provider: config?.provider as ProviderConfig['provider'] ?? 'openai' }),
        availableModels: models,
      });
      setModelSaveStatus('saved');
      setTimeout(() => setModelSaveStatus('idle'), 2000);
    } catch {
      setModelSaveStatus('error');
    }
  }

  return (
    <div className="p-8 space-y-6 max-w-xl">
      <div>
        <h1 className="text-2xl font-bold text-white">Settings</h1>
        <p className="text-gray-400 text-sm mt-1">
          Organization identity and default provider configuration
        </p>
      </div>

      {loading && <p className="text-gray-500 animate-pulse">Loading…</p>}
      {error && <p className="text-red-400 text-sm">{error}</p>}

      {!loading && !error && (
        <>
          {/* Organization Identity */}
          <div className="bg-gray-900 border border-gray-700 rounded-xl p-6 space-y-4">
            <h2 className="text-lg font-semibold text-white">Organization</h2>

            <div>
              <label className="block text-sm font-medium text-gray-300 mb-1">Name</label>
              <input
                type="text"
                value={orgName}
                onChange={(e) => handleOrgNameChange(e.target.value)}
                className="w-full bg-gray-800 border border-gray-600 rounded-lg px-3 py-2 text-gray-100 text-sm focus:outline-none focus:ring-1 focus:ring-blue-500"
                placeholder="My Organization"
              />
            </div>

            <div>
              <div className="flex items-center justify-between mb-1">
                <label className="block text-sm font-medium text-gray-300">Slug</label>
                {!slugAutoGenerated && (
                  <button
                    type="button"
                    onClick={handleAutoGenerateSlug}
                    className="text-xs text-blue-400 hover:text-blue-300"
                  >
                    Auto-generate
                  </button>
                )}
              </div>
              <input
                type="text"
                value={orgSlug}
                onChange={(e) => handleSlugChange(e.target.value.toLowerCase())}
                className={`w-full bg-gray-800 border rounded-lg px-3 py-2 text-gray-100 text-sm font-mono focus:outline-none focus:ring-1 focus:ring-blue-500 ${
                  slugError ? 'border-red-500' : 'border-gray-600'
                }`}
                placeholder="my-organization"
              />
              {slugError && <p className="text-xs text-red-400 mt-1">{slugError}</p>}
              <p className="text-xs text-gray-500 mt-1">Used as the org identifier in artifact references</p>
            </div>

            <div className="flex items-center gap-3">
              <button
                onClick={handleOrgSave}
                disabled={orgSaveStatus === 'saving' || !orgName.trim() || !!slugError}
                className="px-4 py-2 bg-blue-600 hover:bg-blue-500 disabled:opacity-40 disabled:hover:bg-blue-600 text-white text-sm rounded-lg transition-colors"
              >
                {orgSaveStatus === 'saving' ? 'Saving…' : 'Save'}
              </button>
              {orgSaveStatus === 'saved' && <span className="text-xs text-green-400">Saved.</span>}
              {orgSaveStatus === 'error' && <span className="text-xs text-red-400">{orgSaveError}</span>}
            </div>
          </div>

          {/* Org Defaults (Provider Config) */}
          <div className="bg-gray-900 border border-gray-700 rounded-xl p-6 space-y-4">
            <h2 className="text-lg font-semibold text-white">Org Defaults</h2>
            <p className="text-gray-400 text-sm -mt-2">
              Default settings inherited by agents. Agents can override these or leave them blank to use these values.
            </p>

            {config?.provider && (
              <div className="flex items-center gap-2 text-sm text-gray-400 border-b border-gray-700 pb-4">
                <span className="text-green-400">✓</span>
                <span>
                  Currently using <span className="text-gray-200 font-medium">{config.provider}</span>
                  {config.hasApiKey ? ' · API key set' : ''}
                  {config.baseUrl ? ` · ${config.baseUrl}` : ''}
                </span>
              </div>
            )}

            <ProviderConfigForm
              initialConfig={config ?? { provider: null, baseUrl: null, deployment: null, apiVersion: null, hasApiKey: false }}
              onSave={handleSave}
            />

            <div className="border-t border-gray-700 pt-4">
              <ModelListEditor
                models={availableModels}
                onChange={handleModelsChange}
                defaultModels={COMMON_MODELS}
                label="Available Models"
              />
              {modelSaveStatus === 'saving' && <p className="text-xs text-gray-500 mt-2">Saving…</p>}
              {modelSaveStatus === 'saved' && <p className="text-xs text-green-400 mt-2">Saved.</p>}
              {modelSaveStatus === 'error' && <p className="text-xs text-red-400 mt-2">Failed to save model list.</p>}
            </div>

            <p className="text-xs text-gray-500 border-t border-gray-700 pt-4">
              These settings are inherited by all agents in this org unless the agent defines its own.
            </p>
          </div>
        </>
      )}
    </div>
  );
}
